# Generated by Django 4.2.10 on 2026-05-23 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('seo_summary', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('music', 'Music'), ('tech', 'Technology'), ('sports', 'Sports'), ('art', 'Art & Culture'), ('food', 'Food & Drink'), ('business', 'Business'), ('education', 'Education'), ('health', 'Health & Wellness'), ('fashion', 'Fashion'), ('comedy', 'Comedy'), ('other', 'Other')], default='other', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('max_seats', models.PositiveIntegerField(default=100)),
                ('available_seats', models.PositiveIntegerField(default=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_free', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
