# Generated by Django 6.0.5 on 2026-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer'), ('scanner_staff', 'Scanner Staff'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
